apiVersion: apps/v1
kind: Deployment 
metadata:
  name: crud
spec:
 replicas: 1
 selector:
  matchLabels:
   app: crud
 template:
  metadata:
   labels:
    app: crud
  spec:
   containers:
   - name: crud
     image: avena/crud:41
     ports:
       - containerPort: 8080